import { getApiDocs } from "@/lib/swagger";
import ReactSwagger from "./react-swagger";

/**
 * API Documentation Page
 *
 * This page displays the auto-generated Swagger documentation.
 * Navigate to http://localhost:3000/api-doc to view it.
 */
export default async function ApiDocPage() {
  const spec = await getApiDocs();

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto py-8">
        <div className="mb-6 rounded-lg bg-blue-50 p-6 border border-blue-200">
          <h1 className="text-3xl font-bold text-blue-900 mb-2">
            🎉 Auto-Generated API Documentation
          </h1>
          <p className="text-blue-700 mb-4">
            This documentation was automatically generated by{" "}
            <code className="bg-blue-100 px-2 py-1 rounded text-sm">
              next-swagger-doc
            </code>{" "}
            with <strong>60%+ less JSDoc boilerplate!</strong>
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-4">
            <div className="bg-white p-4 rounded border border-blue-200">
              <h3 className="font-semibold text-blue-900 mb-2">
                📝 Minimal JSDoc Mode
              </h3>
              <p className="text-sm text-gray-600">
                Check out <code>/api/users</code> - just a comment, everything
                else is auto-generated!
              </p>
            </div>
            <div className="bg-white p-4 rounded border border-blue-200">
              <h3 className="font-semibold text-blue-900 mb-2">
                🔍 Schema Inference
              </h3>
              <p className="text-sm text-gray-600">
                See <code>/api/users/&#123;id&#125;</code> - schemas
                auto-extracted from Zod and TypeScript types!
              </p>
            </div>
            <div className="bg-white p-4 rounded border border-blue-200">
              <h3 className="font-semibold text-blue-900 mb-2">
                🎨 Hybrid Mode
              </h3>
              <p className="text-sm text-gray-600">
                Explore <code>/api/products</code> - mix auto-gen with explicit
                JSDoc for full control!
              </p>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-lg">
          <ReactSwagger spec={spec} />
        </div>
      </div>
    </div>
  );
}
