/**
 * Merger module - merges auto-generated documentation with explicit JSDoc
 * Explicit JSDoc always takes precedence over auto-generated content
 * @module auto-generate/merger
 */

import type { RouteInfo } from './types';

/**
 * Merges auto-generated route info with explicit JSDoc route info
 * Explicit JSDoc takes precedence at all levels (operation, parameter, response)
 *
 * @param autoGenRoute - Auto-generated route information
 * @param explicitRoute - Explicit route from JSDoc annotations
 * @returns Merged route information with explicit taking precedence
 *
 * @example
 * ```typescript
 * const merged = mergeRouteInfo(autoGen, explicit);
 * // explicit.summary overrides autoGen.summary
 * // explicit.parameters[0] overrides autoGen.parameters[0] if names match
 * ```
 */
export function mergeRouteInfo(
  autoGenRoute: RouteInfo,
  explicitRoute: Partial<RouteInfo>
): RouteInfo {
  // Start with auto-generated as base
  const merged: RouteInfo = { ...autoGenRoute };

  // Override with explicit values at top level
  if (explicitRoute.summary !== undefined) {
    merged.summary = explicitRoute.summary;
  }

  if (explicitRoute.description !== undefined) {
    merged.description = explicitRoute.description;
  }

  if (explicitRoute.tags !== undefined) {
    merged.tags = explicitRoute.tags;
  }

  if (explicitRoute.deprecated !== undefined) {
    merged.deprecated = explicitRoute.deprecated;
  }

  if (explicitRoute.security !== undefined) {
    merged.security = explicitRoute.security;
  }

  // Merge parameters - explicit parameters override auto-generated by name
  if (explicitRoute.parameters) {
    merged.parameters = mergeParameters(
      autoGenRoute.parameters,
      explicitRoute.parameters
    );
  }

  // Merge request body - explicit completely overrides
  if (explicitRoute.requestBody) {
    merged.requestBody = explicitRoute.requestBody;
  }

  // Merge responses - merge by status code
  if (explicitRoute.responses) {
    merged.responses = mergeResponses(
      autoGenRoute.responses,
      explicitRoute.responses
    );
  }

  return merged;
}

/**
 * Merges parameter arrays, with explicit parameters taking precedence
 * Parameters are matched by name and location (in)
 */
function mergeParameters(
  autoGenParams: RouteInfo['parameters'],
  explicitParams: RouteInfo['parameters']
): RouteInfo['parameters'] {
  const merged = [...autoGenParams];

  for (const explicitParam of explicitParams) {
    // Find matching auto-gen param by name and location
    const matchIndex = merged.findIndex(
      (p) => p.name === explicitParam.name && p.in === explicitParam.in
    );

    if (matchIndex !== -1) {
      // Override auto-gen param with explicit
      merged[matchIndex] = {
        ...merged[matchIndex],
        ...explicitParam,
      };
    } else {
      // Add new explicit param
      merged.push(explicitParam);
    }
  }

  return merged;
}

/**
 * Merges response objects by status code
 * Explicit responses override auto-generated responses for same status code
 */
function mergeResponses(
  autoGenResponses: RouteInfo['responses'],
  explicitResponses: RouteInfo['responses']
): RouteInfo['responses'] {
  const merged = { ...autoGenResponses };

  for (const [statusCode, explicitResponse] of Object.entries(explicitResponses)) {
    const code = Number(statusCode);

    if (merged[code]) {
      // Merge response properties, explicit takes precedence
      merged[code] = {
        ...merged[code],
        ...explicitResponse,
      };

      // Deep merge content types if both exist
      if (merged[code].content && explicitResponse.content) {
        merged[code].content = {
          ...merged[code].content,
          ...explicitResponse.content,
        };
      }

      // Deep merge headers if both exist
      if (merged[code].headers && explicitResponse.headers) {
        merged[code].headers = {
          ...merged[code].headers,
          ...explicitResponse.headers,
        };
      }
    } else {
      // Add new explicit response
      merged[code] = explicitResponse;
    }
  }

  return merged;
}

/**
 * Merges multiple route info objects for the same path and method
 * Useful when combining auto-generation with partial overrides
 *
 * @param routes - Array of route info objects (ordered by precedence, last wins)
 * @returns Single merged route info
 */
export function mergeMultipleRoutes(...routes: Array<Partial<RouteInfo>>): RouteInfo | null {
  if (routes.length === 0) {
    return null;
  }

  // Filter out null/undefined
  const validRoutes = routes.filter((r): r is Partial<RouteInfo> => r != null);

  if (validRoutes.length === 0) {
    return null;
  }

  // Start with first route as base
  let merged = validRoutes[0] as RouteInfo;

  // Merge each subsequent route
  for (let i = 1; i < validRoutes.length; i++) {
    merged = mergeRouteInfo(merged, validRoutes[i]);
  }

  return merged;
}

/**
 * Validates that a merged route info is valid OpenAPI
 * Checks required fields and consistency
 *
 * @param route - Route info to validate
 * @returns Validation result with errors
 */
export function validateMergedRoute(route: RouteInfo): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  // Check required fields
  if (!route.routePath) {
    errors.push('Missing required field: routePath');
  }

  if (!route.method) {
    errors.push('Missing required field: method');
  }

  if (!route.responses || Object.keys(route.responses).length === 0) {
    errors.push('At least one response is required');
  }

  // Check path parameters are defined
  const pathParams = route.routePath.match(/\{([^}]+)\}/g) || [];
  for (const paramMatch of pathParams) {
    const paramName = paramMatch.slice(1, -1);
    const param = route.parameters.find((p) => p.name === paramName && p.in === 'path');

    if (!param) {
      errors.push(`Path parameter {${paramName}} is not defined in parameters array`);
    }
  }

  // Check parameter uniqueness
  const paramKeys = new Set<string>();
  for (const param of route.parameters) {
    const key = `${param.in}:${param.name}`;
    if (paramKeys.has(key)) {
      errors.push(`Duplicate parameter: ${param.name} in ${param.in}`);
    }
    paramKeys.add(key);
  }

  // Check response status codes are valid
  for (const statusCode of Object.keys(route.responses)) {
    const code = Number(statusCode);
    if (isNaN(code) || code < 100 || code > 599) {
      errors.push(`Invalid HTTP status code: ${statusCode}`);
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Determines merge strategy based on configuration
 */
export type MergeStrategy = 'explicit-wins' | 'auto-gen-wins' | 'merge-deep';

/**
 * Applies merge strategy to route info objects
 *
 * @param autoGenRoute - Auto-generated route
 * @param explicitRoute - Explicit JSDoc route
 * @param strategy - Merge strategy to use
 * @returns Merged route according to strategy
 */
export function applyMergeStrategy(
  autoGenRoute: RouteInfo,
  explicitRoute: Partial<RouteInfo> | null,
  strategy: MergeStrategy = 'explicit-wins'
): RouteInfo {
  if (!explicitRoute) {
    return autoGenRoute;
  }

  switch (strategy) {
    case 'explicit-wins':
      // Explicit JSDoc completely replaces auto-gen
      return {
        ...autoGenRoute,
        ...explicitRoute,
        // Keep essential fields from auto-gen if not in explicit
        filePath: explicitRoute.filePath || autoGenRoute.filePath,
        routerType: explicitRoute.routerType || autoGenRoute.routerType,
        handler: explicitRoute.handler || autoGenRoute.handler,
      } as RouteInfo;

    case 'auto-gen-wins':
      // Auto-gen completely replaces explicit (rarely used)
      return autoGenRoute;

    case 'merge-deep':
    default:
      // Deep merge with explicit taking precedence (default)
      return mergeRouteInfo(autoGenRoute, explicitRoute);
  }
}

/**
 * Checks if two routes represent the same endpoint
 * (same path and method)
 */
export function isSameEndpoint(
  route1: Pick<RouteInfo, 'routePath' | 'method'>,
  route2: Pick<RouteInfo, 'routePath' | 'method'>
): boolean {
  return route1.routePath === route2.routePath && route1.method === route2.method;
}

/**
 * Groups routes by endpoint (path + method)
 * Useful for finding conflicts between auto-gen and explicit routes
 */
export function groupRoutesByEndpoint(
  routes: RouteInfo[]
): Map<string, RouteInfo[]> {
  const groups = new Map<string, RouteInfo[]>();

  for (const route of routes) {
    const key = `${route.method}:${route.routePath}`;
    const existing = groups.get(key) || [];
    existing.push(route);
    groups.set(key, existing);
  }

  return groups;
}

/**
 * Detects conflicts between auto-generated and explicit routes
 * Returns endpoints that have multiple definitions
 */
export function detectConflicts(
  autoGenRoutes: RouteInfo[],
  explicitRoutes: RouteInfo[]
): Array<{
  endpoint: string;
  autoGen: RouteInfo;
  explicit: RouteInfo;
}> {
  const conflicts: Array<{
    endpoint: string;
    autoGen: RouteInfo;
    explicit: RouteInfo;
  }> = [];

  for (const autoRoute of autoGenRoutes) {
    const matchingExplicit = explicitRoutes.find((e) =>
      isSameEndpoint(autoRoute, e)
    );

    if (matchingExplicit) {
      conflicts.push({
        endpoint: `${autoRoute.method} ${autoRoute.routePath}`,
        autoGen: autoRoute,
        explicit: matchingExplicit,
      });
    }
  }

  return conflicts;
}
