import { join } from 'node:path';
import type { NextApiRequest, NextApiResponse } from 'next';
import swaggerJsdoc, { type OAS3Definition, type Options } from 'swagger-jsdoc';
import type { AutoGenerateConfig } from './auto-generate/config';
import type { RouteInfo } from './auto-generate/types';
import { autoGenerateRoutes } from './auto-generate';

export type SwaggerOptions = Options & {
  apiFolder?: string;
  schemaFolders?: string[];
  definition: OAS3Definition;
  outputFile?: string;
  /**
   * Enable automatic OpenAPI generation from Next.js routes
   * - `true`: Enable with default settings
   * - `false`: Disable (default)
   * - `AutoGenerateConfig`: Enable with custom settings
   */
  autoGenerate?: boolean | Partial<AutoGenerateConfig>;
};

const defaultOptions: SwaggerOptions = {
  apiFolder: 'pages/api',
  schemaFolders: [],
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Next Swagger Doc Demo Api',
      version: '1.0',
    },
  },
};

/**
 * Converts RouteInfo objects to OpenAPI path objects
 *
 * @param routes - Array of auto-generated RouteInfo
 * @returns OpenAPI paths object
 */
function convertRoutesToOpenAPI(routes: RouteInfo[]): Record<string, any> {
  const paths: Record<string, any> = {};

  for (const route of routes) {
    // Initialize path if not exists
    if (!paths[route.routePath]) {
      paths[route.routePath] = {};
    }

    // Convert method to lowercase for OpenAPI
    const method = route.method.toLowerCase();

    // Build operation object
    const operation: any = {
      summary: route.summary,
      description: route.description,
      tags: route.tags,
      parameters: route.parameters.map((param) => ({
        name: param.name,
        in: param.in,
        required: param.required,
        description: param.description,
        schema: param.schema,
        example: param.example,
        deprecated: param.deprecated,
      })),
      responses: {},
    };

    // Convert responses
    for (const [statusCode, response] of Object.entries(route.responses)) {
      operation.responses[statusCode] = {
        description: response.description,
        content: response.content,
        headers: response.headers,
      };
    }

    // Add request body if present
    if (route.requestBody) {
      operation.requestBody = {
        content: {
          [route.requestBody.contentType]: {
            schema: route.requestBody.inlineSchema || {
              $ref: route.requestBody.schemaRef,
            },
          },
        },
      };
    }

    // Add security if present
    if (route.security) {
      operation.security = route.security;
    }

    // Add deprecated flag if present
    if (route.deprecated) {
      operation.deprecated = true;
    }

    paths[route.routePath][method] = operation;
  }

  return paths;
}

/**
 * Merges auto-generated routes with existing swagger spec
 * Explicit JSDoc annotations take precedence over auto-generated
 *
 * @param spec - Existing swagger spec from JSDoc
 * @param routes - Auto-generated routes
 * @returns Merged spec
 */
function mergeAutoGeneratedRoutes(spec: any, routes: RouteInfo[]): any {
  const autoGenPaths = convertRoutesToOpenAPI(routes);

  // Deep merge paths - explicit takes precedence
  const mergedPaths = { ...autoGenPaths };

  if (spec.paths) {
    for (const [path, pathItem] of Object.entries(spec.paths as Record<string, any>)) {
      if (!mergedPaths[path]) {
        mergedPaths[path] = pathItem;
      } else {
        // Merge methods - explicit takes precedence
        mergedPaths[path] = {
          ...mergedPaths[path],
          ...pathItem,
        };
      }
    }
  }

  return {
    ...spec,
    paths: mergedPaths,
  };
}

/**
 * Create swagger JSON
 * @param options.openApiVersion Open API version {3.0.0}
 * @param options.apiFolder NextJS API folder {pages/api}
 * @param options.schemaFolders entity schema folders
 * @param options.title Title
 * @param options.version Version
 * @returns Swagger JSON Spec
 */
export function createSwaggerSpec({
  apiFolder = 'pages/api',
  schemaFolders = [],
  ...swaggerOptions
}: SwaggerOptions = defaultOptions) {
  const scanFolders = [apiFolder, ...schemaFolders];
  const apis = scanFolders.flatMap((folder) => {
    const buildApiDirectory = join(process.cwd(), '.next/server', folder);
    const apiDirectory = join(process.cwd(), folder);
    const publicDirectory = join(process.cwd(), 'public');
    const fileTypes = ['ts', 'tsx', 'jsx', 'js', 'json', 'swagger.yaml'];
    return [
      ...fileTypes.map((fileType) => `${apiDirectory}/**/*.${fileType}`),
      // Only scan build directory for *.swagger.yaml and *.js files
      ...['js', 'swagger.yaml', 'json'].map(
        (fileType) => `${buildApiDirectory}/**/*.${fileType}`
      ),
      // Support load static files from public directory
      ...['swagger.yaml', 'json'].map(
        (fileType) => `${publicDirectory}/**/*.${fileType}`
      ),
    ];
  });

  // Append base path server element to server array
  // Conditions: basePath is specified. Server array is not defined.
  const definition = {
    ...swaggerOptions.definition,
    ...(process.env.__NEXT_ROUTER_BASEPATH &&
      !swaggerOptions.definition.servers && {
        servers: [
          {
            url: process.env.__NEXT_ROUTER_BASEPATH,
            description: 'next-js',
          },
        ],
      }),
  };

  const options: Options = {
    apis, // Files containing annotations as above
    ...swaggerOptions,
    definition,
  };
  let spec = swaggerJsdoc(options);

  // Auto-generation integration (US1 MVP)
  if (swaggerOptions.autoGenerate) {
    const autoGenConfig =
      typeof swaggerOptions.autoGenerate === 'boolean'
        ? { enabled: true }
        : { ...swaggerOptions.autoGenerate, enabled: true };

    try {
      // Generate routes from file structure
      const autoGenRoutes = autoGenerateRoutes(
        join(process.cwd(), apiFolder),
        autoGenConfig
      );

      // Convert to OpenAPI paths and merge with existing spec
      spec = mergeAutoGeneratedRoutes(spec, autoGenRoutes);
    } catch (error) {
      console.warn('[next-swagger-doc] Auto-generation failed:', error);
      // Continue with manual spec if auto-generation fails
    }
  }

  return spec;
}

/**
 * WithSwagger middleware
 * @param options.openApiVersion Open API version {3.0.0}
 * @param options.apiFolder NextJS API folder {pages/api}
 * @param options.schemaFolders entity schema folders
 * @param options.title Title
 * @param options.version Version
 * @returns
 */
export function withSwagger({
  apiFolder = 'pages/api',
  schemaFolders = [],
  ...swaggerOptions
}: SwaggerOptions = defaultOptions) {
  return () => (_req: NextApiRequest, res: NextApiResponse) => {
    try {
      const swaggerSpec = createSwaggerSpec({
        apiFolder,
        schemaFolders,
        ...swaggerOptions,
      });
      res.status(200).send(swaggerSpec);
    } catch (error) {
      res.status(400).send(error);
    }
  };
}
